name: flutter_raw_test_support
description: A utility test project
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^3.4.0

dependencies:
  path: ^1.7.0
  dev_build: '>=0.13.4-dev.1'
  test:

dev_dependencies:
  pedantic: ^1.9.0
