name: Test2
on: push
jobs:
  test:
    name: Test on ${{ matrix.os }} / ${{ matrix.flutter }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            flutter: stable
          - os: ubuntu-latest
            flutter: beta
          - os: ubuntu-latest
            flutter: dev
          - os: windows-latest
            flutter: stable
          - os: macos-latest
            flutter: stable
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '11.x'
      - uses: subosito/flutter-action@v2
        with:
          channel: ${{ matrix.flutter }}
      - run: dart --version
      - run: flutter --version
      - run: flutter upgrade